### ISSUE TITLE
Latest Retail version shows spells as usable, incorrectly. (10.1.6)

### ISSUE THREAD

**Issue by arcadepro** [tullamods/tullaRange#32]
Current version (10.1.5/6 Retail) is little buggy. It causes spells on your bar to light up/desaturate incorrectly. 

Skullsplitter (warrior) is fully lit when its on your bar but untalented. 
Execute (warrior) also is commonly fully saturated when unusable. Hovering over an incorrectly saturated Execute button causes it to update and fix its status temporarily.

This occurs whether the the Tullarange desaturate option is being used or not. So something is causing buttons to go full saturation incorrectly. Removing TullaRange causes execute (and other abilities) to function correctly.

Either it's the new event or the logic is a little wonky somewhere. 

10.1.0 functions correctly.

**Comment by rakkarage** [comment]
testing with execute as spell instead of macro (happens with both but maybe bit different)

- mouse over fixes it!? when looks usable mouse over changes to actual state, not usable
- not happen if right click to start attacking up close but happens when charge
  - quick range and power change?

in `actionButton_UpdateColor`
execute seems to normally return `usable=false oom=false oor=false`
when i charge changes to `usable=false oom=false oor=true`
when i mouse over changes back to `usable=false oom=false oor=false`
so seems like should not show as usable? but does? idk

i guess `actionButton_UpdateColor` needs to be called again or more often? idk
adding hook to `Update` or `OnUpdate` as well seems to fix it soon after charge?

	hooksecurefunc(button, "UpdateUsable", actionButton_UpdateUsable)
	hooksecurefunc(button, "Update", actionButton_UpdateUsable)
	hooksecurefunc(button, "OnUpdate", actionButton_UpdateUsable)

thanks

**Comment by Tuller** [comment]
Blizzard is making some updates to usability changes in 10.2 so that it becomes more event based like range checking is now. I’m waiting to see if that resolves any of the issues

**Comment by arcadepro** [comment]
This is still broken on pre-patch 11.0. Warrior execute being the prime suspect.
